export {default as Home} from './Home'
export {default as Message} from './Message'
export {default as Jobs} from './Jobs'
export {default as More} from './More'
export {default as Register} from './Register'